version: '3.1'

services:

  wpweb:
    image: wpress542
    container_name: wpweb
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: wpdb1.local.io:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /apps/web/html:/var/www/html
      - /apps/web/log:/var/log
